GET http://localhost:8080/student/average/1
Accept: application/json

###
GET http://localhost:8080/student/average/1/1
Accept: application/json

###
POST http://localhost:8080/mark/add
Content-Type: application/json

{
  "studentId": 1,
  "subjectId": 1,
  "value": 2
}

###
GET http://localhost:8080/mark/list
Accept: application/json

###
GET http://localhost:8080/mark/find/1
Accept: application/json

###
POST http://localhost:8080/subject/add
Content-Type: application/json

{
  "name": "matematyka"
}

###
GET http://localhost:8080/subject/find/1
Accept: application/json

###
GET http://localhost:8080/subject/list
Accept: application/json

###
POST http://localhost:8080/techer/add
Content-Type: application/json

{
  "classId": 14,
  "subjectId": 5,
  "name": "Jan",
  "surname": "Kowalski"
}

###
GET http://localhost:8080/techer/list
Accept: application/json

###
GET http://localhost:8080/techer/find/1
Accept: application/json

###
GET http://localhost:8080/student/find/2
Accept: application/json

###
POST http://localhost:8080/student/add
Content-Type: application/json


{
  "name": "Lidia",
  "surname": "Kostka",
  "classId": 10
}


###
GET http://localhost:8080/student/list
Accept: application/json

###
GET http://localhost:8080/class/find/10
Accept: application/json

###
POST http://localhost:8080/class/add
Content-Type: application/json

{
  "className": "3d"

}

###
GET http://localhost:8080/class/list
Accept: application/json

###
